name: Create and publish Docker images

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push main image
      - name: Extract metadata for main image
        id: meta-main
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=dev,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_tag}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=ref,event=tag
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push main Docker image
        id: push-main
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          target: cwa-bd
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BUILD_VERSION=${{ steps.date.outputs.date }}-${{ github.sha }}
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}

      - name: Generate artifact attestation for main image
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-main.outputs.digest }}
          push-to-registry: true

      # Build and push tor image
      - name: Extract metadata for tor image
        id: meta-tor
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-tor
          tags: |
            type=raw,value=dev,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_tag}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=ref,event=tag

      - name: Build and push tor Docker image
        id: push-tor
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          target: cwa-bd-tor
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BUILD_VERSION=${{ steps.date.outputs.date }}-${{ github.sha }}
          tags: ${{ steps.meta-tor.outputs.tags }}
          labels: ${{ steps.meta-tor.outputs.labels }}

      - name: Generate artifact attestation for tor image
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-tor
          subject-digest: ${{ steps.push-tor.outputs.digest }}
          push-to-registry: true

